nelmio_api_doc:
    documentation:
        info:
            title: Sample movie app
            description: This is a sample application with 3 methods to show how problems can be solved
            version: 1.0.0
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/(?!/endpoints$)
        main:
            path_patterns:
                - ^\/((?!_[error|wdt|profiler]).)*$
