services:
  nginx:
    image: nginx:1.25
    volumes:
      - ".:/data/www:cached"
      - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - '80:80'
    depends_on:
      - "php"
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - '.:/data/www:cached'
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - '8082:8080'
    environment:
      SWAGGER_JSON_URL: http://nginx/api/doc.json